import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 221)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.ok_cancel = QtWidgets.QDialogButtonBox(Dialog)
        self.ok_cancel.setGeometry(QtCore.QRect(210, 180, 201, 32))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.ok_cancel.setFont(font)
        self.ok_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_cancel.setOrientation(QtCore.Qt.Horizontal)
        self.ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok_cancel.setObjectName("ok_cancel")
        self.who_are_you = QtWidgets.QLabel(Dialog)
        self.who_are_you.setGeometry(QtCore.QRect(110, 0, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.who_are_you.setFont(font)
        self.who_are_you.setObjectName("who_are_you")
        self.name_of_person = QtWidgets.QLabel(Dialog)
        self.name_of_person.setGeometry(QtCore.QRect(30, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.name_of_person.setFont(font)
        self.name_of_person.setObjectName("name_of_person")
        self.password = QtWidgets.QLabel(Dialog)
        self.password.setGeometry(QtCore.QRect(30, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.name_entry = QtWidgets.QLineEdit(Dialog)
        self.name_entry.setGeometry(QtCore.QRect(160, 70, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.name_entry.setFont(font)
        self.name_entry.setObjectName("name_entry")

        self.name_entry.setFocus()
        self.password_entry = QtWidgets.QLineEdit(Dialog)
        self.password_entry.setGeometry(QtCore.QRect(160, 120, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.password_entry.setFont(font)
        self.password_entry.setObjectName("password_entry")

        self.retranslateUi(Dialog)
        self.ok_cancel.accepted.connect(self.ok_click)
        self.ok_cancel.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Who are you?"))
        self.who_are_you.setText(_translate("Dialog", "Who are you?"))
        self.name_of_person.setText(_translate("Dialog", "Name"))
        self.password.setText(_translate("Dialog", "Password"))

    def ok_click(self):
        name  = self.name_entry.text()
        password = self.password_entry.text()
        print(name ,"  " ,password)
        exit(0)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
